// <auto-generated />
using System;
using MetroClaim.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetroClaim.Api.Migrations
{
    [DbContext(typeof(MetroClaimApiDbContext))]
    [Migration("20251212163929_AddSeeder")]
    partial class AddSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MetroClaim.Api.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("Expired")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("is_used");

                    b.Property<string>("Otp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("otp");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a11111ee-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 965, DateTimeKind.Utc).AddTicks(6191),
                            Email = "admin@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$Xl9BFLBQpbP.dGwUYaVG8e0L6ZWQladp28w5BW82HX5fFUW7pnsSG",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 965, DateTimeKind.Utc).AddTicks(6192),
                            UserId = new Guid("a1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("f11111ee-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 22, 551, DateTimeKind.Utc).AddTicks(7354),
                            Email = "finance@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$8AoVzJkQoCuxXw3lE8Ku/ObI3jfcX0/ZpQ3wBdz5L1HiL9z0bxZYG",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 22, 551, DateTimeKind.Utc).AddTicks(7354),
                            UserId = new Guid("f1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("d10000ff-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 23, 202, DateTimeKind.Utc).AddTicks(4632),
                            Email = "manager1@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$/.P8LgtxsOQcDtd1WF/3huYseDftdQEmSALI.gUxCmhxQ2fFQaQNS",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 23, 202, DateTimeKind.Utc).AddTicks(4632),
                            UserId = new Guid("d1000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e10000ff-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 23, 947, DateTimeKind.Utc).AddTicks(182),
                            Email = "emp1.m1@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$akLAmgzm5w0ktTGyxV3VTOUIJ8vU4bug4qC1vVYwkNwDV2tjVxLbK",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 23, 947, DateTimeKind.Utc).AddTicks(183),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e10000ff-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 24, 526, DateTimeKind.Utc).AddTicks(4490),
                            Email = "emp2.m1@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$cQmhUFtQjRDuZFc9ld8EAuX/gBOmmB4Mz7lt5GGOhpShU3W21y.om",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 24, 526, DateTimeKind.Utc).AddTicks(4491),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e10000ff-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 25, 184, DateTimeKind.Utc).AddTicks(7088),
                            Email = "emp3.m1@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$w0W96BTZVZMMO5wcFF9dduVNv3yaHu60vbZ397cGikIm4onsd2xKq",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 25, 184, DateTimeKind.Utc).AddTicks(7088),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("d20000ff-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 25, 777, DateTimeKind.Utc).AddTicks(919),
                            Email = "manager2@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$RTuCzlhh2F05W0a445pDBOKa0ho36WnjB0X9tZ26Z1inePowLY1Je",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 25, 777, DateTimeKind.Utc).AddTicks(919),
                            UserId = new Guid("d2000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e20000ff-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 26, 435, DateTimeKind.Utc).AddTicks(226),
                            Email = "emp1.m2@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$Y0L28Ls7eM5D5CHUzpHEG.ApIYPILOay6FPktankorj93g2YqeA2i",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 26, 435, DateTimeKind.Utc).AddTicks(226),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e20000ff-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 27, 243, DateTimeKind.Utc).AddTicks(1974),
                            Email = "emp2.m2@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$1EpMeugCbXK9mdBhmW/jw.liYlmaY3E4NY2e9ho/xPtjNLTdjHwBK",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 27, 243, DateTimeKind.Utc).AddTicks(1974),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e20000ff-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 27, 906, DateTimeKind.Utc).AddTicks(5407),
                            Email = "emp3.m2@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$gWyFinTbpXxP0IrHdJEYS.QZ1yEwNaHZ9jam4HW/xvJQh1oH311AG",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 27, 906, DateTimeKind.Utc).AddTicks(5408),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.ApprovalLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalLogStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ReimbursementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reimbursement_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ReimbursementId");

                    b.HasIndex("UserId");

                    b.ToTable("approval_logs", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Limit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("period");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(5113),
                            Limit = 0m,
                            Name = "Trip",
                            Period = "Monthly",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(5114)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(5119),
                            Limit = 5000000m,
                            Name = "Hotel",
                            Period = "Monthly",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(5120)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(5122),
                            Limit = 2000000m,
                            Name = "Transportation",
                            Period = "Monthly",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(5122)
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Reimbursement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("ReimbursementStatus")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("reimbursements", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.ReimbursementItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfExpense")
                        .HasColumnType("date")
                        .HasColumnName("date_of_expenses");

                    b.Property<string>("Receipt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("receipt");

                    b.Property<Guid>("ReimbursementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reimbursement_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReimbursementId");

                    b.ToTable("reimbursement_items", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(4866),
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(4867)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(4870),
                            Name = "Manager",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(4870)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(4872),
                            Name = "Finance",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(4872)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(4874),
                            Name = "Employee",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(4874)
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Destination")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("destination");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("TripStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bank_account_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DueReimbursement")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("due_reimbursement");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("employee_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manager_id");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(5166),
                            DueReimbursement = 0m,
                            EmployeeId = "ADMIN001",
                            FullName = "Admin User",
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 186, DateTimeKind.Utc).AddTicks(5167)
                        },
                        new
                        {
                            Id = new Guid("f1111111-1111-1111-1111-111111111111"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 965, DateTimeKind.Utc).AddTicks(6746),
                            DueReimbursement = 0m,
                            EmployeeId = "FIN001",
                            FullName = "Finance User",
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 965, DateTimeKind.Utc).AddTicks(6746)
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000000"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 22, 551, DateTimeKind.Utc).AddTicks(7491),
                            DueReimbursement = 0m,
                            EmployeeId = "MGR001",
                            FullName = "Manager One",
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 22, 551, DateTimeKind.Utc).AddTicks(7492)
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000001"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 23, 202, DateTimeKind.Utc).AddTicks(4872),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP101",
                            FullName = "Employee 1 (M1)",
                            ManagerId = new Guid("d1000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 23, 202, DateTimeKind.Utc).AddTicks(4872)
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000002"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 23, 947, DateTimeKind.Utc).AddTicks(653),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP102",
                            FullName = "Employee 2 (M1)",
                            ManagerId = new Guid("d1000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 23, 947, DateTimeKind.Utc).AddTicks(654)
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000003"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 24, 526, DateTimeKind.Utc).AddTicks(6039),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP103",
                            FullName = "Employee 3 (M1)",
                            ManagerId = new Guid("d1000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 24, 526, DateTimeKind.Utc).AddTicks(6040)
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000000"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 25, 184, DateTimeKind.Utc).AddTicks(7873),
                            DueReimbursement = 0m,
                            EmployeeId = "MGR002",
                            FullName = "Manager Two",
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 25, 184, DateTimeKind.Utc).AddTicks(7875)
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000001"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 25, 777, DateTimeKind.Utc).AddTicks(1471),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP201",
                            FullName = "Employee 1 (M2)",
                            ManagerId = new Guid("d2000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 25, 777, DateTimeKind.Utc).AddTicks(1473)
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000002"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 26, 435, DateTimeKind.Utc).AddTicks(423),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP202",
                            FullName = "Employee 2 (M2)",
                            ManagerId = new Guid("d2000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 26, 435, DateTimeKind.Utc).AddTicks(423)
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000003"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 27, 243, DateTimeKind.Utc).AddTicks(2391),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP203",
                            FullName = "Employee 3 (M2)",
                            ManagerId = new Guid("d2000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 27, 243, DateTimeKind.Utc).AddTicks(2391)
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.UserLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("LimitUsed")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limit_used");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("user_limits", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a11111bb-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 965, DateTimeKind.Utc).AddTicks(6704),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 21, 965, DateTimeKind.Utc).AddTicks(6705),
                            UserId = new Guid("a1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("f11111bb-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 22, 551, DateTimeKind.Utc).AddTicks(7426),
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 22, 551, DateTimeKind.Utc).AddTicks(7426),
                            UserId = new Guid("f1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("d10000aa-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 23, 202, DateTimeKind.Utc).AddTicks(4703),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 23, 202, DateTimeKind.Utc).AddTicks(4703),
                            UserId = new Guid("d1000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e10000aa-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 23, 947, DateTimeKind.Utc).AddTicks(301),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 23, 947, DateTimeKind.Utc).AddTicks(301),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e10000aa-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 24, 526, DateTimeKind.Utc).AddTicks(4647),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 24, 526, DateTimeKind.Utc).AddTicks(4648),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e10000aa-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 25, 184, DateTimeKind.Utc).AddTicks(7722),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 25, 184, DateTimeKind.Utc).AddTicks(7722),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("d20000aa-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 25, 777, DateTimeKind.Utc).AddTicks(1016),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 25, 777, DateTimeKind.Utc).AddTicks(1017),
                            UserId = new Guid("d2000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e20000aa-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 26, 435, DateTimeKind.Utc).AddTicks(306),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 26, 435, DateTimeKind.Utc).AddTicks(307),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e20000aa-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 27, 243, DateTimeKind.Utc).AddTicks(2251),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 27, 243, DateTimeKind.Utc).AddTicks(2252),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e20000aa-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 39, 27, 906, DateTimeKind.Utc).AddTicks(5487),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 39, 27, 906, DateTimeKind.Utc).AddTicks(5488),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Account", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("MetroClaim.Api.Models.Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.ApprovalLog", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Reimbursement", "Reimbursement")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reimbursement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Reimbursement", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Category", "Category")
                        .WithMany("Reimbursements")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MetroClaim.Api.Models.Trip", "Trip")
                        .WithMany("Reimbursements")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("Reimbursements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.ReimbursementItem", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Reimbursement", "Reimbursement")
                        .WithMany("Items")
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reimbursement");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Trip", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("Trips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.User", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.User", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.UserLimit", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Category", "Category")
                        .WithMany("UserLimits")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("UserLimits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.UserRole", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Category", b =>
                {
                    b.Navigation("Reimbursements");

                    b.Navigation("UserLimits");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Reimbursement", b =>
                {
                    b.Navigation("ApprovalLogs");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Trip", b =>
                {
                    b.Navigation("Reimbursements");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.User", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("ApprovalLogs");

                    b.Navigation("Reimbursements");

                    b.Navigation("Subordinates");

                    b.Navigation("Trips");

                    b.Navigation("UserLimits");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
