// <auto-generated />
using System;
using MetroClaim.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetroClaim.Api.Migrations
{
    [DbContext(typeof(MetroClaimApiDbContext))]
    [Migration("20251212165232_ApplySeedData")]
    partial class ApplySeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MetroClaim.Api.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("Expired")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("is_used");

                    b.Property<string>("Otp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("otp");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a11111ee-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 23, 672, DateTimeKind.Utc).AddTicks(9340),
                            Email = "admin@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$n65b8ftGIBxYtKSVCX3bzunn5RbYJ4NgHZ3pbh0MW9/XzX3te6sMq",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 23, 672, DateTimeKind.Utc).AddTicks(9341),
                            UserId = new Guid("a1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("f11111ee-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 24, 501, DateTimeKind.Utc).AddTicks(2081),
                            Email = "finance@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$.TwX74OX44k/KIrPGPokgO8nUVUOBU2VGpMzO7IYm5x2.AxDo.R.e",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 24, 501, DateTimeKind.Utc).AddTicks(2081),
                            UserId = new Guid("f1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("d10000ff-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 25, 353, DateTimeKind.Utc).AddTicks(2928),
                            Email = "manager1@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$OpwEvyiqQu5CZymE.VxN7eK9CZdFrnW3UqtBsQ86phDCUAPzeSv3q",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 25, 353, DateTimeKind.Utc).AddTicks(2929),
                            UserId = new Guid("d1000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e10000ff-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 26, 176, DateTimeKind.Utc).AddTicks(453),
                            Email = "emp1.m1@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$kWABRKTn9HcYEDPr/w8IWuqPxWbZ8ZqG8PV/gEEej/cy4xMz2LjLe",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 26, 176, DateTimeKind.Utc).AddTicks(454),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e10000ff-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 27, 89, DateTimeKind.Utc).AddTicks(4087),
                            Email = "emp2.m1@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$oJVTD0j5My0VGv/KCFzM5e.T1stPld1KFYmRRHdf5MHlGnZyW32si",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 27, 89, DateTimeKind.Utc).AddTicks(4087),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e10000ff-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 27, 993, DateTimeKind.Utc).AddTicks(2528),
                            Email = "emp3.m1@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$4UVy.fs.sqEC5iG5R/hDc.O/NS9ArczpQ3Pnb.cg8dM3aKL6YNyd2",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 27, 993, DateTimeKind.Utc).AddTicks(2528),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("d20000ff-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 28, 922, DateTimeKind.Utc).AddTicks(636),
                            Email = "manager2@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$T8nsR5KD7olnmHiuLtvcTuds6222D.5JatQxAwctplJ0bt91TxP6O",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 28, 922, DateTimeKind.Utc).AddTicks(637),
                            UserId = new Guid("d2000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e20000ff-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 29, 709, DateTimeKind.Utc).AddTicks(4605),
                            Email = "emp1.m2@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$MjyOGzW/4vcEnpoH0iqO5e2AjBeSuQDmYFrtKqCodHTUSaxyl0s/y",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 29, 709, DateTimeKind.Utc).AddTicks(4606),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e20000ff-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 30, 537, DateTimeKind.Utc).AddTicks(5557),
                            Email = "emp2.m2@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$FuoFsgQ8aacBSijckZ7fweX/hra22MWA.XIQObBlV8uHh0WOY6mWK",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 30, 537, DateTimeKind.Utc).AddTicks(5558),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e20000ff-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 31, 401, DateTimeKind.Utc).AddTicks(4518),
                            Email = "emp3.m2@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$Op7eeL1hDFIF4JjQKejV.ulg5rU0Jds30P1hEC4b/etHGvBpbWuQC",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 31, 401, DateTimeKind.Utc).AddTicks(4518),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.ApprovalLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalLogStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ReimbursementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reimbursement_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ReimbursementId");

                    b.HasIndex("UserId");

                    b.ToTable("approval_logs", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Limit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("period");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2676),
                            Limit = 0m,
                            Name = "Trip",
                            Period = "Monthly",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2678)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2685),
                            Limit = 5000000m,
                            Name = "Hotel",
                            Period = "Monthly",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2685)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2689),
                            Limit = 2000000m,
                            Name = "Transportation",
                            Period = "Monthly",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2689)
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Reimbursement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("ReimbursementStatus")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("reimbursements", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.ReimbursementItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfExpense")
                        .HasColumnType("date")
                        .HasColumnName("date_of_expenses");

                    b.Property<string>("Receipt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("receipt");

                    b.Property<Guid>("ReimbursementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reimbursement_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReimbursementId");

                    b.ToTable("reimbursement_items", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2124),
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2125)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2129),
                            Name = "Manager",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2130)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2132),
                            Name = "Finance",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2132)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2135),
                            Name = "Employee",
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2135)
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Destination")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("destination");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("TripStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bank_account_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DueReimbursement")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("due_reimbursement");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("employee_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manager_id");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2749),
                            DueReimbursement = 0m,
                            EmployeeId = "ADMIN001",
                            FullName = "Admin User",
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 22, 747, DateTimeKind.Utc).AddTicks(2750)
                        },
                        new
                        {
                            Id = new Guid("f1111111-1111-1111-1111-111111111111"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 23, 673, DateTimeKind.Utc).AddTicks(400),
                            DueReimbursement = 0m,
                            EmployeeId = "FIN001",
                            FullName = "Finance User",
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 23, 673, DateTimeKind.Utc).AddTicks(401)
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000000"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 24, 501, DateTimeKind.Utc).AddTicks(2226),
                            DueReimbursement = 0m,
                            EmployeeId = "MGR001",
                            FullName = "Manager One",
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 24, 501, DateTimeKind.Utc).AddTicks(2227)
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000001"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 25, 353, DateTimeKind.Utc).AddTicks(3250),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP101",
                            FullName = "Employee 1 (M1)",
                            ManagerId = new Guid("d1000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 25, 353, DateTimeKind.Utc).AddTicks(3251)
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000002"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 26, 176, DateTimeKind.Utc).AddTicks(1190),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP102",
                            FullName = "Employee 2 (M1)",
                            ManagerId = new Guid("d1000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 26, 176, DateTimeKind.Utc).AddTicks(1190)
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000003"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 27, 89, DateTimeKind.Utc).AddTicks(6148),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP103",
                            FullName = "Employee 3 (M1)",
                            ManagerId = new Guid("d1000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 27, 89, DateTimeKind.Utc).AddTicks(6149)
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000000"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 27, 993, DateTimeKind.Utc).AddTicks(3017),
                            DueReimbursement = 0m,
                            EmployeeId = "MGR002",
                            FullName = "Manager Two",
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 27, 993, DateTimeKind.Utc).AddTicks(3018)
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000001"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 28, 922, DateTimeKind.Utc).AddTicks(1022),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP201",
                            FullName = "Employee 1 (M2)",
                            ManagerId = new Guid("d2000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 28, 922, DateTimeKind.Utc).AddTicks(1023)
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000002"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 29, 709, DateTimeKind.Utc).AddTicks(4815),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP202",
                            FullName = "Employee 2 (M2)",
                            ManagerId = new Guid("d2000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 29, 709, DateTimeKind.Utc).AddTicks(4816)
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000003"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 30, 537, DateTimeKind.Utc).AddTicks(5791),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP203",
                            FullName = "Employee 3 (M2)",
                            ManagerId = new Guid("d2000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 30, 537, DateTimeKind.Utc).AddTicks(5792)
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.UserLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("LimitUsed")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limit_used");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("user_limits", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a11111bb-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 23, 673, DateTimeKind.Utc).AddTicks(323),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 23, 673, DateTimeKind.Utc).AddTicks(323),
                            UserId = new Guid("a1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("f11111bb-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 24, 501, DateTimeKind.Utc).AddTicks(2159),
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 24, 501, DateTimeKind.Utc).AddTicks(2159),
                            UserId = new Guid("f1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("d10000aa-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 25, 353, DateTimeKind.Utc).AddTicks(3028),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 25, 353, DateTimeKind.Utc).AddTicks(3029),
                            UserId = new Guid("d1000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e10000aa-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 26, 176, DateTimeKind.Utc).AddTicks(542),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 26, 176, DateTimeKind.Utc).AddTicks(542),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e10000aa-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 27, 89, DateTimeKind.Utc).AddTicks(4508),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 27, 89, DateTimeKind.Utc).AddTicks(4508),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e10000aa-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 27, 993, DateTimeKind.Utc).AddTicks(2724),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 27, 993, DateTimeKind.Utc).AddTicks(2725),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("d20000aa-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 28, 922, DateTimeKind.Utc).AddTicks(738),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 28, 922, DateTimeKind.Utc).AddTicks(739),
                            UserId = new Guid("d2000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e20000aa-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 29, 709, DateTimeKind.Utc).AddTicks(4688),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 29, 709, DateTimeKind.Utc).AddTicks(4688),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e20000aa-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 30, 537, DateTimeKind.Utc).AddTicks(5659),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 30, 537, DateTimeKind.Utc).AddTicks(5660),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e20000aa-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 12, 16, 52, 31, 401, DateTimeKind.Utc).AddTicks(4613),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 16, 52, 31, 401, DateTimeKind.Utc).AddTicks(4613),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Account", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("MetroClaim.Api.Models.Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.ApprovalLog", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Reimbursement", "Reimbursement")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reimbursement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Reimbursement", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Category", "Category")
                        .WithMany("Reimbursements")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MetroClaim.Api.Models.Trip", "Trip")
                        .WithMany("Reimbursements")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("Reimbursements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.ReimbursementItem", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Reimbursement", "Reimbursement")
                        .WithMany("Items")
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reimbursement");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Trip", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("Trips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.User", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.User", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.UserLimit", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Category", "Category")
                        .WithMany("UserLimits")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("UserLimits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.UserRole", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Category", b =>
                {
                    b.Navigation("Reimbursements");

                    b.Navigation("UserLimits");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Reimbursement", b =>
                {
                    b.Navigation("ApprovalLogs");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Trip", b =>
                {
                    b.Navigation("Reimbursements");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.User", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("ApprovalLogs");

                    b.Navigation("Reimbursements");

                    b.Navigation("Subordinates");

                    b.Navigation("Trips");

                    b.Navigation("UserLimits");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
