// <auto-generated />
using System;
using MetroClaim.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetroClaim.Api.Migrations
{
    [DbContext(typeof(MetroClaimApiDbContext))]
    [Migration("20251212030128_AddSeeder")]
    partial class AddSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MetroClaim.Api.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("Expired")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("is_used");

                    b.Property<string>("Otp")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("otp");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a11111ee-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 22, 187, DateTimeKind.Utc).AddTicks(3851),
                            Email = "admin@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$J9/S0xp87S8D62fyEeqYtuyiLPGtbvpucBTtD0ui6S4hboqKs3N/6",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 22, 187, DateTimeKind.Utc).AddTicks(3857),
                            UserId = new Guid("a1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("f11111ee-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 22, 794, DateTimeKind.Utc).AddTicks(9501),
                            Email = "finance@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$2k65vtwF7/1k3TR/DwmYMe6XPRy3FZ/KS16MY8ozymfqQemTpGWq.",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 22, 794, DateTimeKind.Utc).AddTicks(9502),
                            UserId = new Guid("f1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("d10000ff-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 23, 386, DateTimeKind.Utc).AddTicks(2685),
                            Email = "manager1@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$wT480s7iWmVBwQeHWlfy/O3xQXwAHpNaEAnjWHszupvdSiJLU1VAS",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 23, 386, DateTimeKind.Utc).AddTicks(2686),
                            UserId = new Guid("d1000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e10000ff-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 23, 973, DateTimeKind.Utc).AddTicks(2669),
                            Email = "emp1.m1@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$QSl8IHpknxaJ2qjneFjgoOJchyvDFk5NTpSLeIr4UkBLrX8wQTtHm",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 23, 973, DateTimeKind.Utc).AddTicks(2670),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e10000ff-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 24, 583, DateTimeKind.Utc).AddTicks(4389),
                            Email = "emp2.m1@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$AkF/jHqVwkJ42iWnaHlhBudo782Vqd1CbtjooXBc6k6gHWBcdH6M2",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 24, 583, DateTimeKind.Utc).AddTicks(4389),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e10000ff-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 25, 264, DateTimeKind.Utc).AddTicks(1440),
                            Email = "emp3.m1@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$lID4XD6M7LbxtgSNLN9s2e/VX7k44ZLh1g.XQjlitXm26H/91nVu.",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 25, 264, DateTimeKind.Utc).AddTicks(1440),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("d20000ff-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 25, 890, DateTimeKind.Utc).AddTicks(5506),
                            Email = "manager2@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$kfwkMnZ2IgP1nFQo/LzNTOtcA6n5w2AH0jM/YQwshBMkB67E0ulha",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 25, 890, DateTimeKind.Utc).AddTicks(5507),
                            UserId = new Guid("d2000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e20000ff-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 26, 517, DateTimeKind.Utc).AddTicks(7915),
                            Email = "emp1.m2@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$A4sFbMdkjxrhzE0CrbZAQ.sZ4HnO6J7ZwEkgPhlR5OM2hpYDI0PJi",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 26, 517, DateTimeKind.Utc).AddTicks(7915),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e20000ff-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 27, 102, DateTimeKind.Utc).AddTicks(1536),
                            Email = "emp2.m2@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$MjuQC18tn.KSjRpwFSado.V.qGC/giUqI5pH6kiioBXBw2Pttu/K6",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 27, 102, DateTimeKind.Utc).AddTicks(1536),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e20000ff-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 27, 716, DateTimeKind.Utc).AddTicks(6672),
                            Email = "emp3.m2@metroclaim.com",
                            Expired = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsUsed = false,
                            Password = "$2a$13$5HMsmgMSAi6yWKnWFe2dXebuCubUNBHCI4XdpDk1CcCSo/zh1Y.Mm",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 27, 716, DateTimeKind.Utc).AddTicks(6673),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.ApprovalLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalLogStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ReimbursementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reimbursement_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ReimbursementId");

                    b.HasIndex("UserId");

                    b.ToTable("approval_logs", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Limit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("period");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(2022),
                            Limit = 0m,
                            Name = "Trip",
                            Period = "Monthly",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(2023)
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(2027),
                            Limit = 5000000m,
                            Name = "Hotel",
                            Period = "Monthly",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(2028)
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(2030),
                            Limit = 2000000m,
                            Name = "Transportation",
                            Period = "Monthly",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(2030)
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Reimbursement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("ReimbursementStatus")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("reimbursements", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.ReimbursementItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfExpense")
                        .HasColumnType("date")
                        .HasColumnName("date_of_expenses");

                    b.Property<string>("Receipt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("receipt");

                    b.Property<Guid>("ReimbursementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reimbursement_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReimbursementId");

                    b.ToTable("reimbursement_items", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(1770),
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(1770)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(1772),
                            Name = "Manager",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(1773)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(1774),
                            Name = "Finance",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(1775)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(1826),
                            Name = "Employee",
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(1827)
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Destination")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("destination");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("TripStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("bank_account_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DueReimbursement")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("due_reimbursement");

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("employee_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("manager_id");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("salary");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(2070),
                            DueReimbursement = 0m,
                            EmployeeId = "ADMIN001",
                            FullName = "Admin User",
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 21, 508, DateTimeKind.Utc).AddTicks(2071)
                        },
                        new
                        {
                            Id = new Guid("f1111111-1111-1111-1111-111111111111"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 22, 187, DateTimeKind.Utc).AddTicks(5858),
                            DueReimbursement = 0m,
                            EmployeeId = "FIN001",
                            FullName = "Finance User",
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 22, 187, DateTimeKind.Utc).AddTicks(5860)
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000000"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 22, 794, DateTimeKind.Utc).AddTicks(9624),
                            DueReimbursement = 0m,
                            EmployeeId = "MGR001",
                            FullName = "Manager One",
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 22, 794, DateTimeKind.Utc).AddTicks(9625)
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000001"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 23, 386, DateTimeKind.Utc).AddTicks(2942),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP101",
                            FullName = "Employee 1 (M1)",
                            ManagerId = new Guid("d1000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 23, 386, DateTimeKind.Utc).AddTicks(2942)
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000002"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 23, 973, DateTimeKind.Utc).AddTicks(3504),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP102",
                            FullName = "Employee 2 (M1)",
                            ManagerId = new Guid("d1000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 23, 973, DateTimeKind.Utc).AddTicks(3505)
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000003"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 24, 583, DateTimeKind.Utc).AddTicks(5823),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP103",
                            FullName = "Employee 3 (M1)",
                            ManagerId = new Guid("d1000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 24, 583, DateTimeKind.Utc).AddTicks(5823)
                        },
                        new
                        {
                            Id = new Guid("d2000000-0000-0000-0000-000000000000"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 25, 264, DateTimeKind.Utc).AddTicks(1864),
                            DueReimbursement = 0m,
                            EmployeeId = "MGR002",
                            FullName = "Manager Two",
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 25, 264, DateTimeKind.Utc).AddTicks(1865)
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000001"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 25, 890, DateTimeKind.Utc).AddTicks(5915),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP201",
                            FullName = "Employee 1 (M2)",
                            ManagerId = new Guid("d2000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 25, 890, DateTimeKind.Utc).AddTicks(5915)
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000002"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 26, 517, DateTimeKind.Utc).AddTicks(8172),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP202",
                            FullName = "Employee 2 (M2)",
                            ManagerId = new Guid("d2000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 26, 517, DateTimeKind.Utc).AddTicks(8172)
                        },
                        new
                        {
                            Id = new Guid("e2000000-0000-0000-0000-000000000003"),
                            BankAccountNumber = "1234567890",
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 27, 102, DateTimeKind.Utc).AddTicks(1795),
                            DueReimbursement = 0m,
                            EmployeeId = "EMP203",
                            FullName = "Employee 3 (M2)",
                            ManagerId = new Guid("d2000000-0000-0000-0000-000000000000"),
                            Salary = 10000000m,
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 27, 102, DateTimeKind.Utc).AddTicks(1796)
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.UserLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("LimitUsed")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("limit_used");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("user_limits", (string)null);
                });

            modelBuilder.Entity("MetroClaim.Api.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a11111bb-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 22, 187, DateTimeKind.Utc).AddTicks(5404),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 22, 187, DateTimeKind.Utc).AddTicks(5405),
                            UserId = new Guid("a1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("f11111bb-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 22, 794, DateTimeKind.Utc).AddTicks(9568),
                            RoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 22, 794, DateTimeKind.Utc).AddTicks(9571),
                            UserId = new Guid("f1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("d10000aa-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 23, 386, DateTimeKind.Utc).AddTicks(2754),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 23, 386, DateTimeKind.Utc).AddTicks(2755),
                            UserId = new Guid("d1000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e10000aa-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 23, 973, DateTimeKind.Utc).AddTicks(2780),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 23, 973, DateTimeKind.Utc).AddTicks(2782),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e10000aa-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 24, 583, DateTimeKind.Utc).AddTicks(4531),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 24, 583, DateTimeKind.Utc).AddTicks(4532),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e10000aa-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 25, 264, DateTimeKind.Utc).AddTicks(1587),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 25, 264, DateTimeKind.Utc).AddTicks(1587),
                            UserId = new Guid("e1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("d20000aa-0000-0000-0000-000000000000"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 25, 890, DateTimeKind.Utc).AddTicks(5585),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 25, 890, DateTimeKind.Utc).AddTicks(5586),
                            UserId = new Guid("d2000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e20000aa-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 26, 517, DateTimeKind.Utc).AddTicks(7986),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 26, 517, DateTimeKind.Utc).AddTicks(7987),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("e20000aa-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 27, 102, DateTimeKind.Utc).AddTicks(1615),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 27, 102, DateTimeKind.Utc).AddTicks(1615),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("e20000aa-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 12, 3, 1, 27, 716, DateTimeKind.Utc).AddTicks(6741),
                            RoleId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 12, 3, 1, 27, 716, DateTimeKind.Utc).AddTicks(6742),
                            UserId = new Guid("e2000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Account", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("MetroClaim.Api.Models.Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.ApprovalLog", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Reimbursement", "Reimbursement")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("ApprovalLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reimbursement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Reimbursement", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Category", "Category")
                        .WithMany("Reimbursements")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MetroClaim.Api.Models.Trip", "Trip")
                        .WithMany("Reimbursements")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("Reimbursements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.ReimbursementItem", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Reimbursement", "Reimbursement")
                        .WithMany("Items")
                        .HasForeignKey("ReimbursementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reimbursement");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Trip", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("Trips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.User", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.User", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.UserLimit", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Category", "Category")
                        .WithMany("UserLimits")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("UserLimits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.UserRole", b =>
                {
                    b.HasOne("MetroClaim.Api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetroClaim.Api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Category", b =>
                {
                    b.Navigation("Reimbursements");

                    b.Navigation("UserLimits");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Reimbursement", b =>
                {
                    b.Navigation("ApprovalLogs");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.Trip", b =>
                {
                    b.Navigation("Reimbursements");
                });

            modelBuilder.Entity("MetroClaim.Api.Models.User", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("ApprovalLogs");

                    b.Navigation("Reimbursements");

                    b.Navigation("Subordinates");

                    b.Navigation("Trips");

                    b.Navigation("UserLimits");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
